# Generated by Django 4.2 on 2024-07-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='one_time_password',
            field=models.CharField(default='', max_length=64),
        ),
    ]
