# Generated by Django 4.2 on 2024-07-15 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birt_hday',
            new_name='birth_day',
        ),
    ]
