# Generated by Django 5.0.7 on 2024-07-22 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photolike',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='account',
        ),
        migrations.RemoveField(
            model_name='photolike',
            name='account',
        ),
    ]
