# Generated by Django 5.0.7 on 2024-07-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_alter_photolike_unique_together_remove_photo_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_img',
            field=models.ImageField(blank=True, null=True, upload_to='img_photos'),
        ),
    ]
